# permissions for end users to view poolcoordinators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: poolcoordinator-viewer-role
rules:
- apiGroups:
  - apiextensions.k8s.io.apps.openyurt.io
  resources:
  - poolcoordinators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io.apps.openyurt.io
  resources:
  - poolcoordinators/status
  verbs:
  - get
